const products = [
  {id:1,name:"Vruna",brand:"Nihm",category:"Mobiliario",sub:"Silla",price:"S/ —",material:"Madera",style:"Contemporáneo",color:"Natural",use:"Residencial · Comercial",files:["3D"],tone1:"#e6dfd3",tone2:"#c8bcaa"},
  {id:2,name:"Silla de comedor",brand:"Marca por añadir",category:"Mobiliario",sub:"Silla",price:"S/ —",material:"Madera",style:"Minimalista",color:"Natural",use:"Residencial",files:["CAD","3D"],tone1:"#ded7ca",tone2:"#b8aa98"},
  {id:3,name:"Luminaria decorativa",brand:"Marca por añadir",category:"Iluminación",sub:"Suspensión",price:"S/ —",material:"Metal",style:"Contemporáneo",color:"Negro",use:"Comercial · Hospitality",files:["CAD","3D","BIM"],tone1:"#ddd9d1",tone2:"#a7a197"},
  {id:4,name:"Lavatorio",brand:"Marca por añadir",category:"Baño",sub:"Lavatorio",price:"S/ —",material:"Cerámica",style:"Minimalista",color:"Blanco",use:"Residencial · Comercial",files:["CAD","BIM"],tone1:"#e9e7e1",tone2:"#c7c4bd"},
  {id:5,name:"Porcelanato",brand:"Marca por añadir",category:"Acabados",sub:"Revestimiento",price:"S/ —",material:"Porcelánico",style:"Orgánico",color:"Beige",use:"Todos",files:["Ficha"],tone1:"#ddd3c3",tone2:"#b7aa97"},
  {id:6,name:"Sofá modular",brand:"Marca por añadir",category:"Mobiliario",sub:"Sofá",price:"S/ —",material:"Textil",style:"Contemporáneo",color:"Crudo",use:"Residencial · Hospitality",files:["3D"],tone1:"#e2ddd5",tone2:"#b9b1a6"},
  {id:7,name:"Mesa auxiliar",brand:"Marca por añadir",category:"Mobiliario",sub:"Mesa",price:"S/ —",material:"Piedra",style:"Orgánico",color:"Crema",use:"Residencial",files:["3D"],tone1:"#e2d8c9",tone2:"#b9aa98"},
  {id:8,name:"Aplique mural",brand:"Marca por añadir",category:"Iluminación",sub:"Aplique",price:"S/ —",material:"Metal",style:"Minimalista",color:"Negro",use:"Todos",files:["CAD","BIM"],tone1:"#d9d6d0",tone2:"#9c9992"}
];

const categories=[
 ["🪑","Mobiliario","Sillas, mesas, sofás..."],
 ["💡","Iluminación","Decorativa y técnica"],
 ["🚿","Baño","Sanitarios y griferías"],
 ["🧱","Acabados","Pisos y revestimientos"],
 ["🪵","Maderas","Tableros y enchapes"],
 ["🪨","Piedras","Mármol, cuarzo, sinterizados"],
 ["🧵","Textiles","Telas, cortinas, alfombras"],
 ["🌿","Exterior","Mobiliario y jardín"]
];
const state={filter:{category:"Todos",material:"Todos",style:"Todos",file:"Todos"},favorites:new Set(JSON.parse(localStorage.getItem("ci-favorites")||"[]")),projects:JSON.parse(localStorage.getItem("ci-projects")||"[]")};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("ci-favorites",JSON.stringify([...state.favorites]));localStorage.setItem("ci-projects",JSON.stringify(state.projects));}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function renderCategories(){$("categoryGrid").innerHTML=categories.map(([s,n,d])=>`<article class="category" data-category="${n}"><span class="symbol">${s}</span><div><strong>${n}</strong><small>${d}</small></div></article>`).join("");document.querySelectorAll(".category").forEach(c=>c.onclick=()=>{state.filter.category=c.dataset.category;renderFilters();renderProducts();$("catalogo").scrollIntoView({behavior:"smooth"})})}
function unique(key){return [...new Set(products.map(p=>p[key]))]}
function renderChips(id,values,key){$(id).innerHTML=["Todos",...values].map(v=>`<button class="chip ${state.filter[key]===v?"active":""}" data-key="${key}" data-value="${v}">${v}</button>`).join("");document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=()=>{state.filter[b.dataset.key]=b.dataset.value;renderFilters();renderProducts()})}
function renderFilters(){renderChips("categoryFilters",unique("category"),"category");renderChips("materialFilters",unique("material"),"material");renderChips("styleFilters",unique("style"),"style");renderChips("fileFilters",["CAD","3D","BIM","Ficha"],"file")}
function matches(p){const q=$("searchInput").value.toLowerCase().trim();return(state.filter.category==="Todos"||p.category===state.filter.category)&&(state.filter.material==="Todos"||p.material===state.filter.material)&&(state.filter.style==="Todos"||p.style===state.filter.style)&&(state.filter.file==="Todos"||p.files.includes(state.filter.file))&&(!q||`${p.name} ${p.brand} ${p.category} ${p.sub} ${p.material} ${p.style}`.toLowerCase().includes(q))}
function renderProducts(){const list=products.filter(matches);$("resultsCount").textContent=`${list.length} productos`;$("productGrid").innerHTML=list.length?list.map(p=>`<article class="product-card"><button class="heart ${state.favorites.has(p.id)?"saved":""}" data-id="${p.id}">${state.favorites.has(p.id)?"♥":"♡"}</button><div class="product-image" style="--tone1:${p.tone1};--tone2:${p.tone2}" data-open="${p.id}"><span class="image-label">${p.sub}</span></div><div class="product-info"><div class="product-brand">${p.brand}</div><div class="product-name">${p.name}</div><div class="product-meta"><span>${p.category}</span><span class="product-price">${p.price}</span></div><div class="badges">${p.files.map(f=>`<span class="badge">${f}</span>`).join("")}</div><button class="add-project" data-add="${p.id}">+ Añadir a proyecto</button></div></article>`).join(""):`<p class="empty">No encontramos productos con esos criterios.</p>`;
document.querySelectorAll(".heart").forEach(b=>b.onclick=()=>{const id=+b.dataset.id;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();updateCounts();renderProducts();toast(state.favorites.has(id)?"Guardado en favoritos":"Eliminado de favoritos")});
document.querySelectorAll("[data-open]").forEach(e=>e.onclick=()=>openProduct(+e.dataset.open));
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openProjectPicker(+b.dataset.add));}
function updateCounts(){$("favoriteCount").textContent=state.favorites.size;$("projectCount").textContent=state.projects.length}
function openProduct(id){const p=products.find(x=>x.id===id);$("modalContent").innerHTML=`<div class="modal-content"><div class="modal-image" style="background:linear-gradient(145deg,${p.tone1},${p.tone2})">${p.sub}</div><div class="modal-info"><p class="eyebrow">${p.category} · ${p.sub}</p><h3>${p.name}</h3><div class="brand">${p.brand}</div><div class="detail-grid"><div class="detail"><strong>Material</strong>${p.material}</div><div class="detail"><strong>Estilo</strong>${p.style}</div><div class="detail"><strong>Color</strong>${p.color}</div><div class="detail"><strong>Uso</strong>${p.use}</div><div class="detail"><strong>Precio</strong>${p.price}</div><div class="detail"><strong>Archivos</strong>${p.files.join(" · ")}</div></div><div class="modal-actions"><button class="primary" onclick="openProjectPicker(${p.id});closeModal('productModal')">+ Añadir a proyecto</button><button onclick="toggleFavorite(${p.id})">♡ Favorito</button></div></div></div>`;$("productModal").classList.add("open")}
function closeModal(id){$(id).classList.remove("open")}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();updateCounts();toast("Favoritos actualizados")}
function openDrawer(){$("projectDrawer").classList.add("open");$("drawerBackdrop").classList.add("open");$("projectDrawer").setAttribute("aria-hidden","false");renderProjects()}
function closeDrawer(){$("projectDrawer").classList.remove("open");$("drawerBackdrop").classList.remove("open")}
function renderProjects(){const list=$("projectList");if(!state.projects.length){list.innerHTML=`<div class="empty">Todavía no tienes proyectos.<br>Créalos arriba y luego guarda productos dentro de ellos.</div>`;return}list.innerHTML=state.projects.map((p,i)=>`<article class="project-card"><div class="project-title"><strong>${p.name}</strong><span class="project-count">${p.items.length} productos</span></div>${p.items.length?`<div class="project-items">${p.items.map(id=>{const x=products.find(z=>z.id===id);return `<div class="mini-item">${x?x.name:"Producto"}</div>`}).join("")}</div>`:`<div class="empty">Sin productos todavía.</div>`}</article>`).join("")}
function openProjectPicker(id){if(!state.projects.length){openDrawer();toast("Crea primero un proyecto");return}const options=state.projects.map((p,i)=>`${i+1}. ${p.name}`).join("\\n");const choice=prompt(`¿En qué proyecto quieres guardar este producto?\\n\\n${options}\\n\\nEscribe el número:`);const idx=Number(choice)-1;if(state.projects[idx]){if(!state.projects[idx].items.includes(id))state.projects[idx].items.push(id);save();renderProjects();toast(`Añadido a "${state.projects[idx].name}"`)}}
$("addProjectBtn").onclick=()=>{const name=$("projectNameInput").value.trim();if(!name)return;if(state.projects.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast("Ese proyecto ya existe");state.projects.push({name,items:[]});$("projectNameInput").value="";save();updateCounts();renderProjects();toast("Proyecto creado")}
$("projectsBtn").onclick=openDrawer;$("drawerBackdrop").onclick=closeDrawer;$("favoritesBtn").onclick=()=>{state.filter.category="Todos";state.filter.material="Todos";state.filter.style="Todos";state.filter.file="Todos";$("searchInput").value="";renderProducts();document.getElementById("catalogo").scrollIntoView({behavior:"smooth"});toast(`${state.favorites.size} favoritos guardados`)};
$("searchInput").oninput=renderProducts;$("filterToggle").onclick=()=>{$("filterPanel").classList.toggle("open");$("filterToggle").querySelector("span").textContent=$("filterPanel").classList.contains("open")?"−":"＋"};
$("visualSearchBtn").onclick=()=>toast("Búsqueda visual: la conectaremos en una siguiente versión");
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{if(b.dataset.close==="productModal")closeModal("productModal");else closeDrawer()});
$("productModal").onclick=e=>{if(e.target.id==="productModal")closeModal("productModal")};
renderCategories();renderFilters();renderProducts();updateCounts();
